---- test.`user` definition
--
--CREATE TABLE `user` (
--`id` binary(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
--`email` varchar(255) NOT NULL,
--`login` varchar(255) NOT NULL,
--`password` varchar(255) NOT NULL,
--`user_name` varchar(255) DEFAULT NULL,
--`phone` varchar(100) DEFAULT NULL,
--PRIMARY KEY (`id`)
--) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--
---- test.hotel definition
--
--CREATE TABLE `hotel` (
--`id` binary(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
--`title` varchar(255) DEFAULT NULL,
--`description` varchar(300) DEFAULT NULL,
--`email` varchar(100) NOT NULL,
--`phone` varchar(100) DEFAULT NULL,
--PRIMARY KEY (`id`)
--) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--
---- test.room definition
--
--CREATE TABLE `room` (
--`id` binary(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
--`reserved` bit(1) DEFAULT NULL,
--`room_number` int NOT NULL,
--`type` varchar(255) NOT NULL,
--`start_reserved_date` varchar(255) NOT NULL,
--`end_reserved_date` varchar(255) NOT NULL,
--`hotel_id`  binary(16) DEFAULT NULL,
--`visitor_id`  binary(16) DEFAULT NULL,
--`description` varchar(300) DEFAULT NULL,
--`price` bigint,
--PRIMARY KEY (`id`),
--KEY `room_fk` (`hotel_id`),
--KEY `room_fk_1` (`visitor_id`),
--CONSTRAINT `room_fk` FOREIGN KEY (`hotel_id`) REFERENCES `hotel` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
--CONSTRAINT `room_fk_1` FOREIGN KEY (`visitor_id`) REFERENCES `user` (`id`)
--) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
--
